// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeiXin.DataBase;

namespace WeiXin.Migrations
{
    [DbContext(typeof(AccountContext))]
    [Migration("20180812094619_weixin")]
    partial class weixin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeiXin.Entity.Map", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ManTelphone");

                    b.Property<string>("WomenTelphone");

                    b.HasKey("ID");

                    b.ToTable("Map");
                });

            modelBuilder.Entity("WeiXin.Entity.UserInfo", b =>
                {
                    b.Property<string>("Telphone");

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Address");

                    b.Property<string>("BirthDay");

                    b.Property<string>("College");

                    b.Property<string>("Expect");

                    b.Property<string>("Grade");

                    b.Property<string>("Height");

                    b.Property<string>("Introduce");

                    b.Property<string>("Name");

                    b.Property<string>("QQ");

                    b.Property<string>("Sex");

                    b.Property<string>("WX");

                    b.HasKey("Telphone");

                    b.ToTable("UserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
